dataset_path: validation/vcf/sim_l1mb_0.vcf
output_path: runs/local_refinement_1mb

refinement:
  enabled: true
  arg_path: validation/output/tsinfer/l1mb_dated.trees
  requests:
    - id: region_000001
      genomic_range: [14000, 114000]
      cut_time: 25000

training:
  seed: 7

environment:
  bp_per_blocks: 1
  effective_population_size: 10000
  mutation_rate: 2.0e-8
  recombination_rate: 2.0e-8

reward:
  constant: 30000
